USE krautundrueben;
SET NAMES utf8mb4;

CREATE TABLE REZEPT (
    REZEPTNR      INTEGER NOT NULL,
    REZEPTNAME    VARCHAR(100),
    PORTIONEN     INTEGER,
    ZUBEREITUNG   TEXT,
    PRIMARY KEY (REZEPTNR)
);

CREATE TABLE ERNAEHRUNGSKATEGORIE (
    KATEGORIENR   INTEGER NOT NULL,
    NAME          VARCHAR(50),
    PRIMARY KEY (KATEGORIENR)
);

CREATE TABLE BESCHRAENKUNG (
    BESCHRAENKUNGNR   INTEGER NOT NULL,
    NAME              VARCHAR(50),
    PRIMARY KEY (BESCHRAENKUNGNR)
);

CREATE TABLE REZEPT_ZUTAT (
    REZEPTNR    INTEGER NOT NULL,
    ZUTATENNR   INTEGER NOT NULL,
    MENGE       DECIMAL(10,2),
    EINHEIT     VARCHAR(25),
    PRIMARY KEY (REZEPTNR, ZUTATENNR),
    FOREIGN KEY (REZEPTNR) REFERENCES REZEPT (REZEPTNR),
    FOREIGN KEY (ZUTATENNR) REFERENCES ZUTAT (ZUTATENNR)
);

CREATE TABLE REZEPT_ERNAEHRUNGSKATEGORIE (
    REZEPTNR      INTEGER NOT NULL,
    KATEGORIENR   INTEGER NOT NULL,
    PRIMARY KEY (REZEPTNR, KATEGORIENR),
    FOREIGN KEY (REZEPTNR) REFERENCES REZEPT (REZEPTNR),
    FOREIGN KEY (KATEGORIENR) REFERENCES ERNAEHRUNGSKATEGORIE (KATEGORIENR)
);

CREATE TABLE ZUTAT_BESCHRAENKUNG (
    ZUTATENNR          INTEGER NOT NULL,
    BESCHRAENKUNGNR    INTEGER NOT NULL,
    PRIMARY KEY (ZUTATENNR, BESCHRAENKUNGNR),
    FOREIGN KEY (ZUTATENNR) REFERENCES ZUTAT (ZUTATENNR),
    FOREIGN KEY (BESCHRAENKUNGNR) REFERENCES BESCHRAENKUNG (BESCHRAENKUNGNR)
);
