-- 1. Rezept ↔ Zutat
CREATE TABLE REZEPT_ZUTAT (
    REZEPTNR  INTEGER NOT NULL,
    ZUTATENNR INTEGER NOT NULL,
    MENGE     DECIMAL(10,2),

    PRIMARY KEY (REZEPTNR, ZUTATENNR),

    FOREIGN KEY (REZEPTNR)
        REFERENCES REZEPT (REZEPTNR),

    FOREIGN KEY (ZUTATENNR)
        REFERENCES ZUTAT (ZUTATENNR)
);


-- 2. Rezept ↔ Ernährungskategorie
CREATE TABLE REZEPT_ERNAEHRUNGSKATEGORIE (
    REZEPTNR    INTEGER NOT NULL,
    KATEGORIENR INTEGER NOT NULL,

    PRIMARY KEY (REZEPTNR, KATEGORIENR),

    FOREIGN KEY (REZEPTNR)
        REFERENCES REZEPT (REZEPTNR),

    FOREIGN KEY (KATEGORIENR)
        REFERENCES ERNAEHRUNGSKATEGORIE (KATEGORIENR)
);


-- 3. Zutat ↔ Beschränkung
CREATE TABLE ZUTAT_BESCHRAENKUNG (
    ZUTATENNR       INTEGER NOT NULL,
    BESCHRAENKUNGNR INTEGER NOT NULL,

    PRIMARY KEY (ZUTATENNR, BESCHRAENKUNGNR),

    FOREIGN KEY (ZUTATENNR)
        REFERENCES ZUTAT (ZUTATENNR),

    FOREIGN KEY (BESCHRAENKUNGNR)
        REFERENCES BESCHRAENKUNG (BESCHRAENKUNGNR)
);