-- ============================================================
-- 01_schema.sql  –  Tabellen der Datenbank "krautundrueben"
-- ============================================================
-- Dieses Skript ist die PostgreSQL-Fassung der Vorgabe
--   01_quellen_und_vorgaben/sql_dump_database_create_neu.sql
--
-- Warum eine neue Datei?
--   Die Vorgabe ist in MySQL/MariaDB-Syntax geschrieben
--   (CREATE DATABASE IF NOT EXISTS, USE ..., AUTO_INCREMENT).
--   Das laeuft so NICHT auf PostgreSQL. Die Vorgabe-Dateien
--   bleiben unveraendert; hier steht die portierte Fassung.
--
-- Unterschiede zur Vorgabe (rein syntaktisch, Inhalt gleich):
--   * Kein DROP/CREATE DATABASE und kein USE:
--     Die Datenbank "krautundrueben" wird vom Docker-Container
--     ueber die Umgebungsvariable POSTGRES_DB angelegt.
--   * MySQL "INTEGER AUTO_INCREMENT"
--     -> PostgreSQL "INTEGER GENERATED BY DEFAULT AS IDENTITY"
-- ============================================================

CREATE TABLE KUNDE (
    KUNDENNR     INTEGER NOT NULL,
    NACHNAME     VARCHAR(50),
    VORNAME      VARCHAR(50),
    GEBURTSDATUM DATE,
    STRASSE      VARCHAR(50),
    HAUSNR       VARCHAR(6),
    PLZ          VARCHAR(5),
    ORT          VARCHAR(50),
    TELEFON      VARCHAR(25),
    EMAIL        VARCHAR(50),
    PRIMARY KEY (KUNDENNR)
);

CREATE TABLE LIEFERANT (
    LIEFERANTENNR   INTEGER NOT NULL,
    LIEFERANTENNAME VARCHAR(50),
    STRASSE         VARCHAR(50),
    HAUSNR          VARCHAR(6),
    PLZ             VARCHAR(5),
    ORT             VARCHAR(50),
    TELEFON         VARCHAR(25),
    EMAIL           VARCHAR(50),
    PRIMARY KEY (LIEFERANTENNR)
);

CREATE TABLE ZUTAT (
    ZUTATENNR     INTEGER NOT NULL,
    BEZEICHNUNG   VARCHAR(50),
    EINHEIT       VARCHAR(25),
    NETTOPREIS    DECIMAL(10, 2),
    BESTAND       INTEGER,
    LIEFERANT     INTEGER,
    KALORIEN      INTEGER,
    KOHLENHYDRATE DECIMAL(10, 2),
    PROTEIN       DECIMAL(10, 2),
    PRIMARY KEY (ZUTATENNR),
    FOREIGN KEY (LIEFERANT) REFERENCES LIEFERANT (LIEFERANTENNR)
);

CREATE TABLE BESTELLUNG (
    BESTELLNR       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    KUNDENNR        INTEGER,
    BESTELLDATUM    DATE,
    RECHNUNGSBETRAG DECIMAL(10, 2),
    PRIMARY KEY (BESTELLNR),
    FOREIGN KEY (KUNDENNR) REFERENCES KUNDE (KUNDENNR)
);

CREATE TABLE BESTELLUNGZUTAT (
    BESTELLNR INTEGER NOT NULL,
    ZUTATENNR INTEGER,
    MENGE     INTEGER,
    PRIMARY KEY (BESTELLNR, ZUTATENNR),
    FOREIGN KEY (BESTELLNR) REFERENCES BESTELLUNG (BESTELLNR),
    FOREIGN KEY (ZUTATENNR) REFERENCES ZUTAT (ZUTATENNR)
);
